### ISSUE TITLE
Incomplete Solution to Lab

### ISSUE THREAD

**Issue by meg-gutshall** [learn-co-students/speaking-grandma-v-000#1499]
Hello,

I noticed the solution for this lab is incomplete. It's missing the part where grandma says "I LOVE YOU PUMPKIN!" I submitted a pull request to add my solution to the Learn.co solution branch if you want to take a look.

Take care,
Meg Gutshall

**Comment by trav15** [comment]
I also noticed this error and will add a pull request in case Meg's is not merged. Thank you!

**Comment by drakeltheryuujin** [comment]
Hi there,

Issues with a lesson in the curriculum should be opened on the appropriate repository in `learn-co-curriculum`. 

PRs submitted against `learn-co-curriculum` repositories are reserved for proposed edits and improvements to the curriculum itself.

It looks like this particular issue was resolved on December 8th, 2018 by commit #7517cf8. If this has not been resolved, feel free to reopen this issue.

Thanks for contributing! 💙
