### ISSUE TITLE
There are duplicate tests in the spec/grandma_spec.rb file.

### ISSUE THREAD

**Issue by Sdcrouse** [learn-co-students/speaking-grandma-v-000#1502]
I do not know if this was intentional or accidental, but the last two tests in the spec/grandma_spec.rb file are exactly the same as the first two tests.

Sdcrouse

**Comment by drakeltheryuujin** [comment]
Hi @Sdcrouse,

Issues with a lesson in the curriculum should be opened on the appropriate repository in `learn-co-curriculum`. 

However, I'm having difficulty finding this issue, so I'm going to close it for now.

If you can provide further detail about where you're seeing exact duplicates, I'd be happy to take a second look!

As always, thanks for contributing! 💙

**Comment by Sdcrouse** [comment]
Hi, @drakeltheryuujin,

It looks like the problem got resolved soon after I raised the issue. Although I'm not sure why I'm still getting it on my end, unless new commits don't affect lessons that I've already completed. Here's what my spec file looks like (but again, ONLY on my end):

```
describe '#speak_to_grandma' do
  it 'responds with I LOVE YOU TOO PUMPKIN! if you say I LOVE YOU GRANDMA!' do
    expect(speak_to_grandma('I LOVE YOU GRANDMA!')).to eq 'I LOVE YOU TOO PUMPKIN!'
  end

  it 'responds with HUH?! SPEAK UP, SONNY! unless you are shouting' do
    expect(speak_to_grandma('Hi Nana, how are you?')).to eq 'HUH?! SPEAK UP, SONNY!'
  end

  it 'responds with HUH?! SPEAK UP, SONNY! for a second time' do
    expect(speak_to_grandma('Hi!')).to eq 'HUH?! SPEAK UP, SONNY!'
  end

  it 'responds with NO, NOT SINCE 1938! when she can hear you' do
    expect(speak_to_grandma('WHAT DID YOU EAT TODAY?')).to eq "NO, NOT SINCE 1938!"
  end

  it 'responds with NO, NOT SINCE 1938! for a second time' do
    expect(speak_to_grandma('WHAT?')).to eq "NO, NOT SINCE 1938!"
  end

  it 'responds with I LOVE YOU TOO PUMPKIN! if you say I LOVE YOU GRANDMA!' do
    expect(speak_to_grandma('I LOVE YOU GRANDMA!')).to eq 'I LOVE YOU TOO PUMPKIN!'
  end
 
  it 'responds with HUH?! SPEAK UP, SONNY! unless you are shouting' do
    expect(speak_to_grandma('Hi Nana, how are you?')).to eq 'HUH?! SPEAK UP, SONNY!'
  end

end
```

Some of the tests are exact duplicates. Again, though, that no longer appears to be the case on the Learn repos themselves, just on my local branch.

And as always, you're welcome. Glad to help!

Sdcrouse

**Comment by Sdcrouse** [comment]
OK, I just checked out the commit history. The problem definitely got resolved, at least on this end.
